version: '3'
services:
  quickstart:
    # platform: linux/amd64
    image: stellar/quickstart:soroban-dev
    restart: on-failure
    ports:
      - "8000:8000"
      - "11626:11626"
    command: ["--standalone", "--enable-soroban-rpc", "--enable-core-artificially-accelerate-time-for-testing"]
  ethereum-node:
    build:
      # set build context to the solidity directory
      context: ../solidity
    restart: on-failure
    ports:
      - "8545:8545"
    command: ["npx", "hardhat", "node"]
  deploy-ethereum-contract:
    depends_on:
      - ethereum-node
    build:
      # set build context to the solidity directory
      context: ../solidity
    restart: on-failure
    command: ["npx", "hardhat", "run", "scripts/deploy.js", "--network", "docker"]
    extra_hosts:
      - "host.docker.internal:host-gateway"